--
-- File generated with SQLiteStudio v3.4.4 on ѕт но€ 24 17:34:14 2023
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: Comeets
CREATE TABLE IF NOT EXISTS Comeets (ID INTEGER PRIMARY KEY UNIQUE NOT NULL DEFAULT (1), PersonId INTEGER NOT NULL, Date TEXT NOT NULL, ComeetMessage TEXT NOT NULL);

-- Table: Messages
CREATE TABLE IF NOT EXISTS Messages (ID INTEGER PRIMARY KEY NOT NULL DEFAULT (1) UNIQUE, PersonId INTEGER REFERENCES Persons (ID) NOT NULL, Date TEXT NOT NULL, Amount INTEGER NOT NULL DEFAULT (0));

-- Table: Persons
CREATE TABLE IF NOT EXISTS Persons (ID INTEGER PRIMARY KEY NOT NULL DEFAULT (1) UNIQUE, Name TEXT NOT NULL, LastName TEXT NOT NULL);

-- Table: Tasks
CREATE TABLE IF NOT EXISTS Tasks (ID INTEGER PRIMARY KEY NOT NULL DEFAULT (1) UNIQUE, PersonId REFERENCES Persons (ID) NOT NULL, TaskName TEXT NOT NULL, Changes INTEGER NOT NULL DEFAULT (0), Date TEXT NOT NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
